### ISSUE TITLE
Redirect openapi.by to https://www.openapi.by

### ISSUE THREAD

**Issue by abitrolly** [openapiby/www.openapi.by#2]
Top-level domain like openapi.by can steal cookies from subdomains (or vice versa, I don't remember), and using non-https address allows to steal them from public WiFi networks.

 * http://openapi.by --> https://www.openapi.by
 * https://openapi.by --> https://www.openapi.by
 * http://www.openapi.by --> https://www.openapi.by

**Comment by chertby** [comment]
Defined in htaccess. Check it.

**Comment by abitrolly** [comment]
I don't see it. :( Commit here, to this repo and deploy to Netlify from it?

**Comment by chertby** [comment]
https://openapiby.netlify.com/

**Comment by chertby** [comment]
Done.

**Comment by abitrolly** [comment]
Last redirect does't go HTTPS. See https://www.netlify.com/docs/ssl/ for the fix.

**Comment by chertby** [comment]
Done, forget check a box to force SSL

**Comment by abitrolly** [comment]
Awesome. :+1: ;)
